name: hello_world
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_staggered_grid_view: "^0.3.0"
  dio: ^3.0.8
  awsome_video_player: ^1.0.8+1
  flutter_swiper : ^1.1.6
  cached_network_image: ^2.2.0+1
  photo_view: ^0.9.2
  city_pickers: ^0.1.30
  intl: ^0.16.1
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/navigationbar/bar1.png
    - assets/navigationbar/bar1-a.png
    - assets/navigationbar/bar2.png
    - assets/navigationbar/bar2-a.png
    - assets/navigationbar/bar3.png
    - assets/navigationbar/bar3-a.png
    - assets/navigationbar/bar4.png
    - assets/navigationbar/bar4-a.png
    - assets/home/seach-icon.png
    - assets/home/alert-icon.png
    - assets/home/swiper_decorate_left.png
    - assets/home/swiper_decorate_right.png
    - assets/home/loading.png
    - assets/test_video.mp4
    - assets/details/details_loading.gif
    - assets/user/user-fn-fb.png
    - assets/user/user-fn-collect.png
    - assets/user/user-fn-whome.png
    - assets/user/user-fn-ly.png
    - assets/user/user-fn-rz.png
    - assets/user/user-dw-order.png
    - assets/user/user-dw-position.png
    - assets/user/user-dw-aq.png
    - assets/user/user-dw-opinion.png
    - assets/user/user-dw-about.png
    - assets/user/user-dw-logout.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/iconfont/iconfont.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
